name: 'PHP CI/CD'
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
      - run: composer install --prefer-dist --optimize-autoloader
      - run: php -v
      - run: php bin/console
      