name: 'CI/CD - Symfony Demo Application'
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: 'intl, mbstring, pdo_sqlite'
          php-version: '8.1'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock', 'vendor/bin/.phpunit/phpunit/composer.lock') }}
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: "Install PHPUnit"
        run: vendor/bin/simple-phpunit install
      - name: Run tests
        run: php bin/phpunit
