name: 'CI/CD - Symfony Demo Application'
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: cyrillelamal/setup-symfony-app@v1
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     extensions: 'intl, mbstring, pdo_sqlite'
      #     php-version: '8.1'
      #     tools: 'php-cs-fixer, composer'
      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # - name: Install dependencies
      #   run: composer install --no-interaction --no-progress
      - name: Run tests
        run: php bin/phpunit
  
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: cyrillelamal/setup-symfony-app@v1
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     extensions: 'intl, mbstring, pdo_sqlite'
      #     php-version: '8.1'
      #     tools: 'php-cs-fixer, composer'
      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      # - name: Install dependencies
      #   run: composer install --no-interaction --no-progress
      - name: Lint DI container
        run: php bin/console lint:container
      - name: Add Twig linter dependencies
        run: composer require --dev twig/inky-extra twig/cssinliner-extra
      - name: Lint Twig templates
        run: php bin/console lint:twig
      - name: Lint translation files
        run: php bin/console lint:xliff translations
      - name: Lint configuration files
        run: php bin/console lint:yaml config
