name: 'Dependency scan'
on:
  schedule:
    - cron: '10 15 * * *'
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: cyrillelamal/setup-symfony-app@v3
      - name: Check if any dependencies are compromised
        run: symfony check:security
